---
version: '2'
services:
  web:
    image: crowdflower/testing
    entrypoint: bundle exec
    build: "."
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
    - 3000:3000
    volumes:
    - ".:/app"
    depends_on:
    - postgres
  postgres:
    image: crowdflower/ai-postgres
    volumes:
    - pg-storage:/var/lib/postgresql/data
    ports:
    - 5432:5432
volumes:
  pg-storage: 
