development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

test:
  <<: *default
  database: css_test

sandbox:
  <<: *default

qa:
  <<: *default

live:
  <<: *default
