# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7debe307a6f030204ee4e8e8c40bd77f0ccd7498b4bd8e97be6faca172c4df9ad9b89ef1b7384e1a0fe419c374f40173cbe9e3c9f7fa39c692a7efa0a360f18e

test:
  secret_key_base: a0e9f8d66fbca789723892718faf0f82d6044dd3f7238263b6b0f230786aa2d312e113d15b30b09afa9daf6a20db3d136660ed4aafe4a94aedd00d02c3cddf34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
